import { Zone } from '@/types';

export interface MaterialPrice {
  name: string;
  list_price: number;
  store_price: number;
  sell_back: number;
}

// Page 2: The Price List (Published at The Reveal)
export const materialPriceList: MaterialPrice[] = [
  { name: 'Water', list_price: 400, store_price: 480, sell_back: 240 },
  { name: 'Food', list_price: 600, store_price: 720, sell_back: 360 },
  { name: 'Metal', list_price: 800, store_price: 960, sell_back: 480 },
  { name: 'Glass', list_price: 1200, store_price: 1440, sell_back: 720 },
  { name: 'Plastic', list_price: 3000, store_price: 3600, sell_back: 1800 },
  { name: 'Power', list_price: 3500, store_price: 4200, sell_back: 2100 },
  { name: 'Chemicals', list_price: 7000, store_price: 8400, sell_back: 4200 },
  { name: 'Medicine', list_price: 11000, store_price: 13200, sell_back: 6600 },
];

export const regionalInformation: Record<string, { description: string; known_for: string }> = {
  'The Delta': {
    description: 'Flooded river land and coastal marsh.',
    known_for: 'Water and Food',
  },
  'The Ash Belt': {
    description: 'Active vent fields and burning flats.',
    known_for: 'Power and Chemicals',
  },
  'The Spine': {
    description: 'High mountain ridges and deep quarry mines.',
    known_for: 'Metal and Glass',
  },
  'The Hollow': {
    description: 'Subterranean transit tunnels and ancient sealed vaults.',
    known_for: 'Plastic and Medicine',
  },
  'The Grid': {
    description: 'Autonomous core infrastructure, computational relays, and high-tech fabrication facilities.',
    known_for: 'Data, Synthesis, and Automation',
  },
};

export const officialZones: Zone[] = [
  // ============================================================
  // ZONE 1 — SEDGEMOUTH
  // ============================================================
  {
    id: 'zone_01',
    zone_number: 1,
    name: 'SEDGEMOUTH',
    region: 'The Delta',
    next_to: '2, 6',
    neighboring_zones: '2, 6',
    starting_price: 44000,
    description: 'A low-lying settlement on a floodplain around a damaged river vessel.',
    terrain: 'A low-lying settlement on a floodplain around a damaged river vessel.',
    space: 60,
    stock: 'Water 50 · Food 30',
    used: 80,
    free: -20,
    free_text: '-20 OVER CAPACITY — show in red',
    worth: 'SEALED',
    // Unlocks at The Reveal
    water_price: 400,
    food_price: 600,
    zone_value: 38000,
    worth_per_arc: 0.86,
    total_raw_material_value: 38000,
    zone_total_value: 38000,
    final_value: 38000,
    generation_output_value: 'Water 50 · Food 30 (38,000 ARK)',
    deposits: 'Water, Food',
    in_the_ground: 'Water 50 · Food 30',
    makes: 'Water 50 · Food 30',
    yield: 'Water 50 · Food 30 (38,000 ARK)',
    raw_materials: [
      { name: 'Water', quantity: 50, unit: 'loads', price: 400, total_value: 20000 },
      { name: 'Food', quantity: 30, unit: 'loads', price: 600, total_value: 18000 },
    ],
    // Unlocks in Round 2
    problem: 'The river is breaking through the old flood wall.',
    fix_material: 'Metal',
    fix_qty: 8,
    zone_has_it: 'No — this zone holds none',
    if_not_fixed: 'A third of everything the zone holds is washed away.',
    people: 'Three families live exactly where the new wall has to go. ARKK moved them here four years ago and they will not move again.',
    budget: '10000 grant + whatever the team saved',
    // Unlocks in Round 5
    trades: 'Water — the zone holds 50 loads',
    split_a: 'Drinking water — 2 loads of water makes 1',
    split_b: 'Industrial water — 1 load of water makes 1',
    wanted_by: 'Zone 13 wants 6 drinking water\nZone 16 wants 20 industrial water',
    splits_once: true,
    spoils: true,
    round_5_material: 'Water',
    status: 'available',
  },

  // ============================================================
  // ZONE 2 — REEDFALL
  // ============================================================
  {
    id: 'zone_02',
    zone_number: 2,
    name: 'REEDFALL',
    region: 'The Delta',
    next_to: '1, 3, 7',
    neighboring_zones: '1, 3, 7',
    starting_price: 26000,
    description: 'A reed marsh with old water gates. Food and plastic in the silt.',
    terrain: 'A reed marsh with old water gates. Food and plastic in the silt.',
    space: 45,
    stock: 'Food 34 · Plastic 3',
    used: 37,
    free: 8,
    free_text: '8',
    worth: 'SEALED',
    // Unlocks at The Reveal
    food_price: 600,
    plastic_price: 3000,
    zone_value: 29400,
    worth_per_arc: 1.13,
    total_raw_material_value: 29400,
    zone_total_value: 29400,
    final_value: 29400,
    generation_output_value: 'Food 34 · Plastic 3 (29,400 ARK)',
    deposits: 'Food, Plastic',
    in_the_ground: 'Food 34 · Plastic 3',
    makes: 'Food 34 · Plastic 3',
    yield: 'Food 34 · Plastic 3 (29,400 ARK)',
    raw_materials: [
      { name: 'Food', quantity: 34, unit: 'loads', price: 600, total_value: 20400 },
      { name: 'Plastic', quantity: 3, unit: 'loads', price: 3000, total_value: 9000 },
    ],
    // Unlocks in Round 2
    problem: 'The water gates have rusted shut.',
    fix_material: 'Metal',
    fix_qty: 6,
    zone_has_it: 'No — this zone holds none',
    if_not_fixed: 'The marsh drains and the food halves.',
    people: 'The gate keepers say the gates are unsafe to work and have walked off.',
    budget: '10000 grant + whatever the team saved',
    // Unlocks in Round 5
    trades: 'Food — the zone holds 34 loads',
    split_a: 'Grain — 2 loads of food makes 1',
    split_b: 'Animal feed — 1 load of food makes 1',
    wanted_by: 'Zone 16 wants 8 grain\nZone 10 wants 4 animal feed',
    splits_once: true,
    spoils: true,
    round_5_material: 'Food',
    status: 'available',
  },

  // ============================================================
  // ZONE 3 — LOWWATER
  // ============================================================
  {
    id: 'zone_03',
    zone_number: 3,
    name: 'LOWWATER',
    region: 'The Delta',
    next_to: '2, 4, 8',
    neighboring_zones: '2, 4, 8',
    starting_price: 30000,
    description: 'Drained farmland with pump houses along the dyke.',
    terrain: 'Drained farmland with pump houses along the dyke.',
    space: 35,
    stock: 'Food 26 · Water 20',
    used: 46,
    free: -11,
    free_text: '-11 OVER CAPACITY — show in red',
    worth: 'SEALED',
    // Unlocks at The Reveal
    food_price: 600,
    water_price: 400,
    zone_value: 23600,
    worth_per_arc: 0.79,
    total_raw_material_value: 23600,
    zone_total_value: 23600,
    final_value: 23600,
    generation_output_value: 'Food 26 · Water 20 (23,600 ARK)',
    deposits: 'Food, Water',
    in_the_ground: 'Food 26 · Water 20',
    makes: 'Food 26 · Water 20',
    yield: 'Food 26 · Water 20 (23,600 ARK)',
    raw_materials: [
      { name: 'Food', quantity: 26, unit: 'loads', price: 600, total_value: 15600 },
      { name: 'Water', quantity: 20, unit: 'loads', price: 400, total_value: 8000 },
    ],
    // Unlocks in Round 2
    problem: 'The pumps that keep the field drained have failed.',
    fix_material: 'Power',
    fix_qty: 2,
    zone_has_it: 'No — this zone holds none',
    if_not_fixed: 'The field floods and the zone holds nothing at all.',
    people: 'The pump operators want to be paid in food, not ARK. They say ARK does not feed anyone.',
    budget: '10000 grant + whatever the team saved',
    // Unlocks in Round 5
    trades: 'Food — the zone holds 26 loads',
    split_a: 'Grain — 2 loads of food makes 1',
    split_b: 'Animal feed — 1 load of food makes 1',
    wanted_by: 'Zone 7 wants 12 grain\nZone 15 wants 4 animal feed',
    splits_once: true,
    spoils: true,
    round_5_material: 'Food',
    status: 'available',
  },

  // ============================================================
  // ZONE 4 — BRACKMERE
  // ============================================================
  {
    id: 'zone_04',
    zone_number: 4,
    name: 'BRACKMERE',
    region: 'The Delta',
    next_to: '3, 5, 9',
    neighboring_zones: '3, 5, 9',
    starting_price: 17000,
    description: 'A salt lake with scrub. Water everywhere, none of it drinkable yet.',
    terrain: 'A salt lake with scrub. Water everywhere, none of it drinkable yet.',
    space: 25,
    stock: 'Water 22',
    used: 22,
    free: 3,
    free_text: '3',
    worth: 'SEALED',
    // Unlocks at The Reveal
    water_price: 400,
    zone_value: 8800,
    worth_per_arc: 0.52,
    total_raw_material_value: 8800,
    zone_total_value: 8800,
    final_value: 8800,
    generation_output_value: 'Water 22 (8,800 ARK)',
    deposits: 'Water',
    in_the_ground: 'Water 22',
    makes: 'Water 22',
    yield: 'Water 22 (8,800 ARK)',
    raw_materials: [
      { name: 'Water', quantity: 22, unit: 'loads', price: 400, total_value: 8800 },
    ],
    // Unlocks in Round 2
    problem: 'The lake water is too salty to drink.',
    fix_material: 'Glass',
    fix_qty: 2,
    zone_has_it: 'No — this zone holds none',
    if_not_fixed: 'Nobody can use the water. The zone is worthless.',
    people: 'The fishing families have blocked the site where the filters must go. It is their only landing.',
    budget: '10000 grant + whatever the team saved',
    // Unlocks in Round 5
    trades: 'Water — the zone holds 22 loads',
    split_a: 'Drinking water — 2 loads of water makes 1',
    split_b: 'Industrial water — 1 load of water makes 1',
    wanted_by: 'Zone 16 wants 20 industrial water\nZone 7 wants 8 drinking water',
    splits_once: true,
    spoils: true,
    round_5_material: 'Water',
    status: 'available',
  },

  // ============================================================
  // ZONE 5 — SILTGATE
  // ============================================================
  {
    id: 'zone_05',
    zone_number: 5,
    name: 'SILTGATE',
    region: 'The Delta',
    next_to: '4, 10',
    neighboring_zones: '4, 10',
    starting_price: 15000,
    description: 'A silt barrier with a stuck gate. Glass sand below the waterline.',
    terrain: 'A silt barrier with a stuck gate. Glass sand below the waterline.',
    space: 25,
    stock: 'Water 14 · Glass 5',
    used: 19,
    free: 6,
    free_text: '6',
    worth: 'SEALED',
    // Unlocks at The Reveal
    water_price: 400,
    glass_price: 1200,
    zone_value: 11600,
    worth_per_arc: 0.77,
    total_raw_material_value: 11600,
    zone_total_value: 11600,
    final_value: 11600,
    generation_output_value: 'Water 14 · Glass 5 (11,600 ARK)',
    deposits: 'Water, Glass',
    in_the_ground: 'Water 14 · Glass 5',
    makes: 'Water 14 · Glass 5',
    yield: 'Water 14 · Glass 5 (11,600 ARK)',
    raw_materials: [
      { name: 'Water', quantity: 14, unit: 'loads', price: 400, total_value: 5600 },
      { name: 'Glass', quantity: 5, unit: 'loads', price: 1200, total_value: 6000 },
    ],
    // Unlocks in Round 2
    problem: 'The barrier gate is jammed shut with silt.',
    fix_material: 'Metal',
    fix_qty: 5,
    zone_has_it: 'No — this zone holds none',
    if_not_fixed: 'The barrier cannot be opened and the zone stops.',
    people: 'The lock crew left for the Delta last season. Two old hands remain and they want double.',
    budget: '10000 grant + whatever the team saved',
    // Unlocks in Round 5
    trades: 'Water — the zone holds 14 loads',
    split_a: 'Drinking water — 2 loads of water makes 1',
    split_b: 'Industrial water — 1 load of water makes 1',
    wanted_by: 'Zone 14 wants 10 drinking water\nZone 18 wants 8 industrial water',
    splits_once: true,
    spoils: true,
    round_5_material: 'Water',
    status: 'available',
  },

  // ============================================================
  // ZONE 6 — CINDERFALL
  // ============================================================
  {
    id: 'zone_06',
    zone_number: 6,
    name: 'CINDERFALL',
    region: 'The Ash Belt',
    next_to: '1, 7, 11',
    neighboring_zones: '1, 7, 11',
    starting_price: 10000,
    description: 'An ash slope above an active vent field. Hot ground, bad air.',
    terrain: 'An ash slope above an active vent field. Hot ground, bad air.',
    space: 45,
    stock: 'Power 10 · Chemicals 1',
    used: 11,
    free: 34,
    free_text: '34',
    worth: 'SEALED',
    // Unlocks at The Reveal
    power_price: 3500,
    chemicals_price: 7000,
    zone_value: 42000,
    worth_per_arc: 4.20,
    total_raw_material_value: 42000,
    zone_total_value: 42000,
    final_value: 42000,
    generation_output_value: 'Power 10 · Chemicals 1 (42,000 ARK)',
    deposits: 'Power, Chemicals',
    in_the_ground: 'Power 10 · Chemicals 1',
    makes: 'Power 10 · Chemicals 1',
    yield: 'Power 10 · Chemicals 1 (42,000 ARK)',
    raw_materials: [
      { name: 'Power', quantity: 10, unit: 'loads', price: 3500, total_value: 35000 },
      { name: 'Chemicals', quantity: 1, unit: 'loads', price: 7000, total_value: 7000 },
    ],
    // Unlocks in Round 2
    problem: 'Ash in the air is making the workers sick.',
    fix_material: 'Medicine',
    fix_qty: 1,
    zone_has_it: 'No — this zone holds none',
    if_not_fixed: 'Output drops by a fifth.',
    people: "The workers' families are at the gate. They want medicine for their children before anyone goes back in.",
    budget: '10000 grant + whatever the team saved',
    // Unlocks in Round 5
    trades: 'Power — the zone holds 10 loads',
    split_a: 'Mains supply — 1 load of power makes 1',
    split_b: 'Battery packs — 2 loads of power makes 1',
    wanted_by: 'Zone 12 wants 4 mains supply\nZone 14 wants 2 battery packs',
    splits_once: true,
    spoils: true,
    round_5_material: 'Power',
    status: 'available',
  },

  // ============================================================
  // ZONE 7 — FUMAROLE
  // ============================================================
  {
    id: 'zone_07',
    zone_number: 7,
    name: 'FUMAROLE',
    region: 'The Ash Belt',
    next_to: '2, 6, 8, 12',
    neighboring_zones: '2, 6, 8, 12',
    starting_price: 14000,
    description: 'A field of steam vents that never cools.',
    terrain: 'A field of steam vents that never cools.',
    space: 60,
    stock: 'Power 16',
    used: 16,
    free: 44,
    free_text: '44',
    worth: 'SEALED',
    // Unlocks at The Reveal
    power_price: 3500,
    zone_value: 56000,
    worth_per_arc: 4.00,
    total_raw_material_value: 56000,
    zone_total_value: 56000,
    final_value: 56000,
    generation_output_value: 'Power 16 (56,000 ARK)',
    deposits: 'Power',
    in_the_ground: 'Power 16',
    makes: 'Power 16',
    yield: 'Power 16 (56,000 ARK)',
    raw_materials: [
      { name: 'Power', quantity: 16, unit: 'loads', price: 3500, total_value: 56000 },
    ],
    // Unlocks in Round 2
    problem: 'The steam is eating through the pipes.',
    fix_material: 'Metal',
    fix_qty: 20,
    zone_has_it: 'No — this zone holds none',
    if_not_fixed: 'Output falls a quarter, and keeps falling.',
    people: 'The pipe crew says the vent field is not safe to work any more. They have walked out.',
    budget: '10000 grant + whatever the team saved',
    // Unlocks in Round 5
    trades: 'Power — the zone holds 16 loads',
    split_a: 'Mains supply — 1 load of power makes 1',
    split_b: 'Battery packs — 2 loads of power makes 1',
    wanted_by: 'Zone 11 wants 3 mains supply\nZone 19 wants 3 battery packs',
    splits_once: true,
    spoils: true,
    round_5_material: 'Power',
    status: 'available',
  },

  // ============================================================
  // ZONE 8 — SLAGMOUTH
  // ============================================================
  {
    id: 'zone_08',
    zone_number: 8,
    name: 'SLAGMOUTH',
    region: 'The Ash Belt',
    next_to: '3, 7, 9, 13',
    neighboring_zones: '3, 7, 9, 13',
    starting_price: 22000,
    description: 'A fallen-in furnace and waste heaps. Metal and glass in the ground.',
    terrain: 'A fallen-in furnace and waste heaps. Metal and glass in the ground.',
    space: 35,
    stock: 'Metal 24 · Glass 6',
    used: 30,
    free: 5,
    free_text: '5',
    worth: 'SEALED',
    // Unlocks at The Reveal
    metal_price: 800,
    glass_price: 1200,
    zone_value: 26400,
    worth_per_arc: 1.20,
    total_raw_material_value: 26400,
    zone_total_value: 26400,
    final_value: 26400,
    generation_output_value: 'Metal 24 · Glass 6 (26,400 ARK)',
    deposits: 'Metal, Glass',
    in_the_ground: 'Metal 24 · Glass 6',
    makes: 'Metal 24 · Glass 6',
    yield: 'Metal 24 · Glass 6 (26,400 ARK)',
    raw_materials: [
      { name: 'Metal', quantity: 24, unit: 'loads', price: 800, total_value: 19200 },
      { name: 'Glass', quantity: 6, unit: 'loads', price: 1200, total_value: 7200 },
    ],
    // Unlocks in Round 2
    problem: 'The furnace has gone out and must be relit.',
    fix_material: 'Power',
    fix_qty: 3,
    zone_has_it: 'No — this zone holds none',
    if_not_fixed: 'Two full working periods are lost.',
    people: 'The furnace crew sleeps on site. They want proper quarters built before they go back.',
    budget: '10000 grant + whatever the team saved',
    // Unlocks in Round 5
    trades: 'Metal — the zone holds 24 loads',
    split_a: 'Beams — 3 loads of metal makes 1',
    split_b: 'Filings — 2 loads of metal makes 1',
    wanted_by: 'Zone 13 wants 6 beams\nZone 20 wants 10 filings',
    splits_once: true,
    spoils: true,
    round_5_material: 'Metal',
    status: 'available',
  },

  // ============================================================
  // ZONE 9 — EMBERWATCH
  // ============================================================
  {
    id: 'zone_09',
    zone_number: 9,
    name: 'EMBERWATCH',
    region: 'The Ash Belt',
    next_to: '4, 8, 10, 14',
    neighboring_zones: '4, 8, 10, 14',
    starting_price: 8000,
    description: 'A watch post on the ridge above the vent field. Exposed, but it sees everything.',
    terrain: 'A watch post on the ridge above the vent field. Exposed, but it sees everything.',
    space: 35,
    stock: 'Power 7 · Chemicals 1',
    used: 8,
    free: 27,
    free_text: '27',
    worth: 'SEALED',
    // Unlocks at The Reveal
    power_price: 3500,
    chemicals_price: 7000,
    zone_value: 31500,
    worth_per_arc: 3.94,
    total_raw_material_value: 31500,
    zone_total_value: 31500,
    final_value: 31500,
    generation_output_value: 'Power 7 · Chemicals 1 (31,500 ARK)',
    deposits: 'Power, Chemicals',
    in_the_ground: 'Power 7 · Chemicals 1',
    makes: 'Power 7 · Chemicals 1',
    yield: 'Power 7 · Chemicals 1 (31,500 ARK)',
    raw_materials: [
      { name: 'Power', quantity: 7, unit: 'loads', price: 3500, total_value: 24500 },
      { name: 'Chemicals', quantity: 1, unit: 'loads', price: 7000, total_value: 7000 },
    ],
    // Unlocks in Round 2
    problem: 'Ash is getting into the vents and they need sealing.',
    fix_material: 'Glass',
    fix_qty: 4,
    zone_has_it: 'No — this zone holds none',
    if_not_fixed: 'Power output drops until it is fixed.',
    people: 'The vent crew will not climb up any more. The ash is making them sick and they are not wrong.',
    budget: '10000 grant + whatever the team saved',
    // Unlocks in Round 5
    trades: 'Power — the zone holds 7 loads',
    split_a: 'Mains supply — 1 load of power makes 1',
    split_b: 'Battery packs — 2 loads of power makes 1',
    wanted_by: 'Zone 12 wants 4 mains supply\nZone 14 wants 3 battery packs',
    splits_once: true,
    spoils: true,
    round_5_material: 'Power',
    status: 'available',
  },

  // ============================================================
  // ZONE 10 — CAUSTIC FLATS
  // ============================================================
  {
    id: 'zone_10',
    zone_number: 10,
    name: 'CAUSTIC FLATS',
    region: 'The Ash Belt',
    next_to: '5, 9, 15',
    neighboring_zones: '5, 9, 15',
    starting_price: 6000,
    description: 'Drying pans on burnt ground. Almost nothing here, but what is here is rare.',
    terrain: 'Drying pans on burnt ground. Almost nothing here, but what is here is rare.',
    space: 25,
    stock: 'Chemicals 1 · Glass 4',
    used: 5,
    free: 20,
    free_text: '20',
    worth: 'SEALED',
    // Unlocks at The Reveal
    chemicals_price: 7000,
    glass_price: 1200,
    zone_value: 11800,
    worth_per_arc: 1.97,
    total_raw_material_value: 11800,
    zone_total_value: 11800,
    final_value: 11800,
    generation_output_value: 'Chemicals 1 · Glass 4 (11,800 ARK)',
    deposits: 'Chemicals, Glass',
    in_the_ground: 'Chemicals 1 · Glass 4',
    makes: 'Chemicals 1 · Glass 4',
    yield: 'Chemicals 1 · Glass 4 (11,800 ARK)',
    raw_materials: [
      { name: 'Chemicals', quantity: 1, unit: 'loads', price: 7000, total_value: 7000 },
      { name: 'Glass', quantity: 4, unit: 'loads', price: 1200, total_value: 4800 },
    ],
    // Unlocks in Round 2
    problem: 'The ground is eating through the drying pans.',
    fix_material: 'Metal',
    fix_qty: 3,
    zone_has_it: 'No — this zone holds none',
    if_not_fixed: 'The pans break open and the chemicals are lost.',
    people: 'Only two families know how to work the pans. They want a share of what comes out, not wages.',
    budget: '10000 grant + whatever the team saved',
    // Unlocks in Round 5
    trades: 'Chemicals — the zone holds 1 loads',
    split_a: 'Liquid — 2 loads of chemicals makes 1',
    split_b: 'Powder — 1 load of chemicals makes 1',
    wanted_by: 'Zone 18 wants 4 powder\nZone 2 wants 2 liquid',
    splits_once: true,
    spoils: true,
    round_5_material: 'Chemicals',
    status: 'available',
  },

  // ============================================================
  // ZONE 11 — COLDGATE
  // ============================================================
  {
    id: 'zone_11',
    zone_number: 11,
    name: 'COLDGATE',
    region: 'The Spine',
    next_to: '6, 12, 16',
    neighboring_zones: '6, 12, 16',
    starting_price: 21000,
    description: 'A fort guarding the mountain pass. Everything moving north goes past its gate.',
    terrain: 'A fort guarding the mountain pass. Everything moving north goes past its gate.',
    space: 45,
    stock: 'Metal 26 · Plastic 3',
    used: 29,
    free: 16,
    free_text: '16',
    worth: 'SEALED',
    // Unlocks at The Reveal
    metal_price: 800,
    plastic_price: 3000,
    zone_value: 29800,
    worth_per_arc: 1.42,
    total_raw_material_value: 29800,
    zone_total_value: 29800,
    final_value: 29800,
    generation_output_value: 'Metal 26 · Plastic 3 (29,800 ARK)',
    deposits: 'Metal, Plastic',
    in_the_ground: 'Metal 26 · Plastic 3',
    makes: 'Metal 26 · Plastic 3',
    yield: 'Metal 26 · Plastic 3 (29,800 ARK)',
    raw_materials: [
      { name: 'Metal', quantity: 26, unit: 'loads', price: 800, total_value: 20800 },
      { name: 'Plastic', quantity: 3, unit: 'loads', price: 3000, total_value: 9000 },
    ],
    // Unlocks in Round 2
    problem: 'The pass has iced over and the gate is frozen shut.',
    fix_material: 'Power',
    fix_qty: 3,
    zone_has_it: 'No — this zone holds none',
    if_not_fixed: 'Nothing moves through the pass. The zone earns nothing.',
    people: 'The gate guards have taken the gate house. They say they have held that pass for years and were never paid.',
    budget: '10000 grant + whatever the team saved',
    // Unlocks in Round 5
    trades: 'Metal — the zone holds 26 loads',
    split_a: 'Beams — 3 loads of metal makes 1',
    split_b: 'Filings — 2 loads of metal makes 1',
    wanted_by: 'Zone 13 wants 6 beams\nZone 7 wants 20 filings',
    splits_once: true,
    spoils: true,
    round_5_material: 'Metal',
    status: 'available',
  },

  // ============================================================
  // ZONE 12 — IRONFAST
  // ============================================================
  {
    id: 'zone_12',
    zone_number: 12,
    name: 'IRONFAST',
    region: 'The Spine',
    next_to: '7, 11, 13, 17',
    neighboring_zones: '7, 11, 13, 17',
    starting_price: 25000,
    description: 'An open ridge above a mine cut into for sixty years. The lower shafts are deep.',
    terrain: 'An open ridge above a mine cut into for sixty years. The lower shafts are deep.',
    space: 60,
    stock: 'Metal 30 · Chemicals 4',
    used: 34,
    free: 26,
    free_text: '26',
    worth: 'SEALED',
    // Unlocks at The Reveal
    metal_price: 800,
    chemicals_price: 7000,
    zone_value: 52000,
    worth_per_arc: 2.08,
    total_raw_material_value: 52000,
    zone_total_value: 52000,
    final_value: 52000,
    generation_output_value: 'Metal 30 · Chemicals 4 (52,000 ARK)',
    deposits: 'Metal, Chemicals',
    in_the_ground: 'Metal 30 · Chemicals 4',
    makes: 'Metal 30 · Chemicals 4',
    yield: 'Metal 30 · Chemicals 4 (52,000 ARK)',
    raw_materials: [
      { name: 'Metal', quantity: 30, unit: 'loads', price: 800, total_value: 24000 },
      { name: 'Chemicals', quantity: 4, unit: 'loads', price: 7000, total_value: 28000 },
    ],
    // Unlocks in Round 2
    problem: 'Water is coming into the mine. The pumps are broken.',
    fix_material: 'Power',
    fix_qty: 4,
    zone_has_it: 'No — this zone holds none',
    if_not_fixed: 'Half the metal is ruined — 15 loads, worth 12,000.',
    people: 'The pump crew has stopped working. The pay is too low and their families are sick. The pump house is theirs and nobody gets in without them.',
    budget: '10000 grant + whatever the team saved',
    // Unlocks in Round 5
    trades: 'Metal — the zone holds 30 loads',
    split_a: 'Beams — 3 loads of metal makes 1',
    split_b: 'Filings — 2 loads of metal makes 1',
    wanted_by: 'Zone 13 wants 6 beams\nZone 9 wants 8 filings',
    splits_once: true,
    spoils: true,
    round_5_material: 'Metal',
    status: 'available',
  },

  // ============================================================
  // ZONE 13 — COLDSPUR
  // ============================================================
  {
    id: 'zone_13',
    zone_number: 13,
    name: 'COLDSPUR',
    region: 'The Spine',
    next_to: '8, 12, 14, 18',
    neighboring_zones: '8, 12, 14, 18',
    starting_price: 7000,
    description: 'A frozen ridge. No buildings, no road in. Nobody has worked it since the collapse.',
    terrain: 'A frozen ridge. No buildings, no road in. Nobody has worked it since the collapse.',
    space: 25,
    stock: 'Chemicals 7',
    used: 7,
    free: 18,
    free_text: '18',
    worth: 'SEALED',
    // Unlocks at The Reveal
    chemicals_price: 7000,
    zone_value: 49000,
    worth_per_arc: 7.00,
    total_raw_material_value: 49000,
    zone_total_value: 49000,
    final_value: 49000,
    generation_output_value: 'Chemicals 7 (49,000 ARK)',
    deposits: 'Chemicals',
    in_the_ground: 'Chemicals 7',
    makes: 'Chemicals 7',
    yield: 'Chemicals 7 (49,000 ARK)',
    raw_materials: [
      { name: 'Chemicals', quantity: 7, unit: 'loads', price: 7000, total_value: 49000 },
    ],
    // Unlocks in Round 2
    problem: 'The shelters on the ridge are coming down.',
    fix_material: 'Metal',
    fix_qty: 20,
    zone_has_it: 'No — this zone holds none',
    if_not_fixed: 'Nobody can work the seam. The zone holds nothing.',
    people: 'The crew refuses to go up without shelter, and they are right. It is a frozen ridge with no buildings.',
    budget: '10000 grant + whatever the team saved',
    // Unlocks in Round 5
    trades: 'Chemicals — the zone holds 7 loads',
    split_a: 'Liquid — 2 loads of chemicals makes 1',
    split_b: 'Powder — 1 load of chemicals makes 1',
    wanted_by: 'Zone 12 wants 4 liquid\nZone 14 wants 4 powder',
    splits_once: true,
    spoils: true,
    round_5_material: 'Chemicals',
    status: 'available',
  },

  // ============================================================
  // ZONE 14 — GRANITE HOLD
  // ============================================================
  {
    id: 'zone_14',
    zone_number: 14,
    name: 'GRANITE HOLD',
    region: 'The Spine',
    next_to: '9, 13, 15, 19',
    neighboring_zones: '9, 13, 15, 19',
    starting_price: 20000,
    description: 'Quarry steps cut into the west face. Good stone, glass sand in the lower cuts.',
    terrain: 'Quarry steps cut into the west face. Good stone, glass sand in the lower cuts.',
    space: 35,
    stock: 'Metal 20 · Glass 8',
    used: 28,
    free: 7,
    free_text: '7',
    worth: 'SEALED',
    // Unlocks at The Reveal
    metal_price: 800,
    glass_price: 1200,
    zone_value: 25600,
    worth_per_arc: 1.28,
    total_raw_material_value: 25600,
    zone_total_value: 25600,
    final_value: 25600,
    generation_output_value: 'Metal 20 · Glass 8 (25,600 ARK)',
    deposits: 'Metal, Glass',
    in_the_ground: 'Metal 20 · Glass 8',
    makes: 'Metal 20 · Glass 8',
    yield: 'Metal 20 · Glass 8 (25,600 ARK)',
    raw_materials: [
      { name: 'Metal', quantity: 20, unit: 'loads', price: 800, total_value: 16000 },
      { name: 'Glass', quantity: 8, unit: 'loads', price: 1200, total_value: 9600 },
    ],
    // Unlocks in Round 2
    problem: 'The cutting tools on the quarry face have no power.',
    fix_material: 'Power',
    fix_qty: 2,
    zone_has_it: 'No — this zone holds none',
    if_not_fixed: 'The face cannot be cut and the quarry stops.',
    people: 'The quarry crew has not been paid for two working periods and has downed tools.',
    budget: '10000 grant + whatever the team saved',
    // Unlocks in Round 5
    trades: 'Glass — the zone holds 8 loads',
    split_a: 'Sheets — 2 loads of glass makes 1',
    split_b: 'Sand — 1 load of glass makes 1',
    wanted_by: 'Zone 9 wants 4 sheets\nZone 13 wants 6 sand',
    splits_once: true,
    spoils: true,
    round_5_material: 'Glass',
    status: 'available',
  },

  // ============================================================
  // ZONE 15 — HIGH ADIT
  // ============================================================
  {
    id: 'zone_15',
    zone_number: 15,
    name: 'HIGH ADIT',
    region: 'The Spine',
    next_to: '10, 14, 20',
    neighboring_zones: '10, 14, 20',
    starting_price: 10000,
    description: 'A high tunnel mouth, open only in season. One way in, one way out.',
    terrain: 'A high tunnel mouth, open only in season. One way in, one way out.',
    space: 25,
    stock: 'Metal 11',
    used: 11,
    free: 14,
    free_text: '14',
    worth: 'SEALED',
    // Unlocks at The Reveal
    metal_price: 800,
    zone_value: 8800,
    worth_per_arc: 0.88,
    total_raw_material_value: 8800,
    zone_total_value: 8800,
    final_value: 8800,
    generation_output_value: 'Metal 11 (8,800 ARK)',
    deposits: 'Metal',
    in_the_ground: 'Metal 11',
    makes: 'Metal 11',
    yield: 'Metal 11 (8,800 ARK)',
    raw_materials: [
      { name: 'Metal', quantity: 11, unit: 'loads', price: 800, total_value: 8800 },
    ],
    // Unlocks in Round 2
    problem: 'Snow has blocked the tunnel mouth.',
    fix_material: 'Power',
    fix_qty: 1,
    zone_has_it: 'No — this zone holds none',
    if_not_fixed: 'Nobody can get in and nothing comes out.',
    people: 'One family knows the way in and out in this season. They want paying whether the tunnel opens or not.',
    budget: '10000 grant + whatever the team saved',
    // Unlocks in Round 5
    trades: 'Metal — the zone holds 11 loads',
    split_a: 'Beams — 3 loads of metal makes 1',
    split_b: 'Filings — 2 loads of metal makes 1',
    wanted_by: 'Zone 10 wants 3 beams\nZone 5 wants 5 filings',
    splits_once: true,
    spoils: true,
    round_5_material: 'Metal',
    status: 'available',
  },

  // ============================================================
  // ZONE 16 — UNDERKEEP
  // ============================================================
  {
    id: 'zone_016',
    zone_number: 16,
    name: 'UNDERKEEP',
    region: 'The Hollow',
    next_to: '11, 17',
    neighboring_zones: '11, 17',
    starting_price: 7000,
    description: 'Sealed vault rooms under the old city. Most have never been opened.',
    terrain: 'Sealed vault rooms under the old city. Most have never been opened.',
    space: 45,
    stock: 'Medicine 3 · Plastic 3',
    used: 6,
    free: 39,
    free_text: '39',
    worth: 'SEALED',
    // Unlocks at The Reveal
    medicine_price: 11000,
    plastic_price: 3000,
    zone_value: 42000,
    worth_per_arc: 6.00,
    total_raw_material_value: 42000,
    zone_total_value: 42000,
    final_value: 42000,
    generation_output_value: 'Medicine 3 · Plastic 3 (42,000 ARK)',
    deposits: 'Medicine, Plastic',
    in_the_ground: 'Medicine 3 · Plastic 3',
    makes: 'Medicine 3 · Plastic 3',
    yield: 'Medicine 3 · Plastic 3 (42,000 ARK)',
    raw_materials: [
      { name: 'Medicine', quantity: 3, unit: 'loads', price: 11000, total_value: 33000 },
      { name: 'Plastic', quantity: 3, unit: 'loads', price: 3000, total_value: 9000 },
    ],
    // Unlocks in Round 2
    problem: 'The vault rooms must stay clean or the medicine spoils.',
    fix_material: 'Water',
    fix_qty: 20,
    zone_has_it: 'No — this zone holds none',
    if_not_fixed: 'The whole stock of medicine is ruined.',
    people: 'Locals have taken the key to the lower rooms. They want medicine for their own people first.',
    budget: '10000 grant + whatever the team saved',
    // Unlocks in Round 5
    trades: 'Medicine — the zone holds 3 loads',
    split_a: 'Tablets — 2 loads of medicine makes 1',
    split_b: 'Disinfectant — 1 load of medicine makes 1',
    wanted_by: 'Zone 6 wants 1 tablets\nZone 9 wants 1 disinfectant',
    splits_once: true,
    spoils: true,
    round_5_material: 'Medicine',
    status: 'available',
  },

  // ============================================================
  // ZONE 17 — DEEPCACHE
  // ============================================================
  {
    id: 'zone_017',
    zone_number: 17,
    name: 'DEEPCACHE',
    region: 'The Hollow',
    next_to: '12, 16, 18',
    neighboring_zones: '12, 16, 18',
    starting_price: 4000,
    description: 'Store rooms below the old transit ring. Cold, dry and largely untouched.',
    terrain: 'Store rooms below the old transit ring. Cold, dry and largely untouched.',
    space: 35,
    stock: 'Medicine 2',
    used: 2,
    free: 33,
    free_text: '33',
    worth: 'SEALED',
    // Unlocks at The Reveal
    medicine_price: 11000,
    zone_value: 22000,
    worth_per_arc: 5.50,
    total_raw_material_value: 22000,
    zone_total_value: 22000,
    final_value: 22000,
    generation_output_value: 'Medicine 2 (22,000 ARK)',
    deposits: 'Medicine',
    in_the_ground: 'Medicine 2',
    makes: 'Medicine 2',
    yield: 'Medicine 2 (22,000 ARK)',
    raw_materials: [
      { name: 'Medicine', quantity: 2, unit: 'loads', price: 11000, total_value: 22000 },
    ],
    // Unlocks in Round 2
    problem: 'The store rooms must stay cold.',
    fix_material: 'Power',
    fix_qty: 2,
    zone_has_it: 'No — this zone holds none',
    if_not_fixed: 'The medicine spoils and is worth nothing.',
    people: 'The store keepers have been quietly selling stock for years. They will not hand over the keys.',
    budget: '10000 grant + whatever the team saved',
    // Unlocks in Round 5
    trades: 'Medicine — the zone holds 2 loads',
    split_a: 'Tablets — 2 loads of medicine makes 1',
    split_b: 'Disinfectant — 1 load of medicine makes 1',
    wanted_by: 'Zone 11 wants 1 tablets\nZone 12 wants 1 disinfectant',
    splits_once: true,
    spoils: true,
    round_5_material: 'Medicine',
    status: 'available',
  },

  // ============================================================
  // ZONE 18 — LOWARCH
  // ============================================================
  {
    id: 'zone_018',
    zone_number: 18,
    name: 'LOWARCH',
    region: 'The Hollow',
    next_to: '13, 17, 19',
    neighboring_zones: '13, 17, 19',
    starting_price: 14000,
    description: 'A fallen arcade with the lower halls still standing.',
    terrain: 'A fallen arcade with the lower halls still standing.',
    space: 45,
    stock: 'Plastic 11 · Metal 6',
    used: 17,
    free: 28,
    free_text: '28',
    worth: 'SEALED',
    // Unlocks at The Reveal
    plastic_price: 3000,
    metal_price: 800,
    zone_value: 37800,
    worth_per_arc: 2.70,
    total_raw_material_value: 37800,
    zone_total_value: 37800,
    final_value: 37800,
    generation_output_value: 'Plastic 11 · Metal 6 (37,800 ARK)',
    deposits: 'Plastic, Metal',
    in_the_ground: 'Plastic 11 · Metal 6',
    makes: 'Plastic 11 · Metal 6',
    yield: 'Plastic 11 · Metal 6 (37,800 ARK)',
    raw_materials: [
      { name: 'Plastic', quantity: 11, unit: 'loads', price: 3000, total_value: 33000 },
      { name: 'Metal', quantity: 6, unit: 'loads', price: 800, total_value: 4800 },
    ],
    // Unlocks in Round 2
    problem: 'The lower halls are ready to cave in.',
    fix_material: 'Glass',
    fix_qty: 8,
    zone_has_it: 'No — this zone holds none',
    if_not_fixed: 'The halls are sealed off and most of the stock is lost.',
    people: 'Scavenger families have been living in the lower halls since the collapse. Nobody has told them to leave.',
    budget: '10000 grant + whatever the team saved',
    // Unlocks in Round 5
    trades: 'Plastic — the zone holds 11 loads',
    split_a: 'Sheeting — 2 loads of plastic makes 1',
    split_b: 'Pipes — 1 load of plastic makes 1',
    wanted_by: 'Zone 19 wants 4 sheeting\nZone 3 wants 2 pipes',
    splits_once: true,
    spoils: true,
    round_5_material: 'Plastic',
    status: 'available',
  },

  // ============================================================
  // ZONE 19 — THE STACKS
  // ============================================================
  {
    id: 'zone_019',
    zone_number: 19,
    name: 'THE STACKS',
    region: 'The Hollow',
    next_to: '14, 18, 20',
    neighboring_zones: '14, 18, 20',
    starting_price: 13000,
    description: 'Old record floors, part flooded. Nothing down there has been catalogued.',
    terrain: 'Old record floors, part flooded. Nothing down there has been catalogued.',
    space: 35,
    stock: 'Plastic 8 · Glass 8',
    used: 16,
    free: 19,
    free_text: '19',
    worth: 'SEALED',
    // Unlocks at The Reveal
    plastic_price: 3000,
    glass_price: 1200,
    zone_value: 33600,
    worth_per_arc: 2.58,
    total_raw_material_value: 33600,
    zone_total_value: 33600,
    final_value: 33600,
    generation_output_value: 'Plastic 8 · Glass 8 (33,600 ARK)',
    deposits: 'Plastic, Glass',
    in_the_ground: 'Plastic 8 · Glass 8',
    makes: 'Plastic 8 · Glass 8',
    yield: 'Plastic 8 · Glass 8 (33,600 ARK)',
    raw_materials: [
      { name: 'Plastic', quantity: 8, unit: 'loads', price: 3000, total_value: 24000 },
      { name: 'Glass', quantity: 8, unit: 'loads', price: 1200, total_value: 9600 },
    ],
    // Unlocks in Round 2
    problem: 'Water is coming into the lower floors.',
    fix_material: 'Power',
    fix_qty: 3,
    zone_has_it: 'No — this zone holds none',
    if_not_fixed: 'The lower floors are lost along with what is stored there.',
    people: 'The archivists will not let the floors be pumped with machines. They say it will destroy what is down there.',
    budget: '10000 grant + whatever the team saved',
    // Unlocks in Round 5
    trades: 'Glass — the zone holds 8 loads',
    split_a: 'Sheets — 2 loads of glass makes 1',
    split_b: 'Sand — 1 load of glass makes 1',
    wanted_by: 'Zone 9 wants 4 sheets\nZone 5 wants 5 sand',
    splits_once: true,
    spoils: true,
    round_5_material: 'Glass',
    status: 'available',
  },

  // ============================================================
  // ZONE 20 — NULLWARD
  // ============================================================
  {
    id: 'zone_020',
    zone_number: 20,
    name: 'NULLWARD',
    region: 'The Hollow',
    next_to: '15, 19',
    neighboring_zones: '15, 19',
    starting_price: 5000,
    description: 'A shielded lower floor. ARKK records list it as empty.',
    terrain: 'A shielded lower floor. ARKK records list it as empty.',
    space: 25,
    stock: 'Medicine 4',
    used: 4,
    free: 21,
    free_text: '21',
    worth: 'SEALED',
    // Unlocks at The Reveal
    medicine_price: 11000,
    zone_value: 44000,
    worth_per_arc: 8.80,
    total_raw_material_value: 44000,
    zone_total_value: 44000,
    final_value: 44000,
    generation_output_value: 'Medicine 4 (44,000 ARK)',
    deposits: 'Medicine',
    in_the_ground: 'Medicine 4',
    makes: 'Medicine 4',
    yield: 'Medicine 4 (44,000 ARK)',
    raw_materials: [
      { name: 'Medicine', quantity: 4, unit: 'loads', price: 11000, total_value: 44000 },
    ],
    // Unlocks in Round 2
    problem: 'The radiation shield is failing.',
    fix_material: 'Metal',
    fix_qty: 10,
    zone_has_it: 'No — this zone holds none',
    if_not_fixed: 'The floor is poisoned and the zone is worth nothing ever again.',
    people: 'Nobody will go down there. The one crew that will has asked for three times normal pay.',
    budget: '10000 grant + whatever the team saved',
    // Unlocks in Round 5
    trades: 'Medicine — the zone holds 4 loads',
    split_a: 'Tablets — 2 loads of medicine makes 1',
    split_b: 'Disinfectant — 1 load of medicine makes 1',
    wanted_by: 'Zone 6 wants 1 tablets\nZone 17 wants 2 disinfectant',
    splits_once: true,
    spoils: true,
    round_5_material: 'Medicine',
    status: 'available',
  },

  // ============================================================
  // ZONE 21 — THE ORACLE
  // ============================================================
  {
    id: 'zone_21',
    zone_number: 21,
    name: 'THE ORACLE',
    region: 'The Grid',
    next_to: '16, 22',
    neighboring_zones: '16, 22',
    starting_price: 9000,
    description: "The Oracle is ARKK's artificial intelligence decision core, buried in a cooled hall beneath the Grid Region.",
    terrain: "The Oracle is ARKK's artificial intelligence decision core, buried in a cooled hall beneath the Grid Region.",
    space: 25,
    stock: 'Chemicals 5 · Plastic 4',
    used: 9,
    free: 16,
    free_text: '16',
    worth: 'SEALED',
    // Unlocks at The Reveal
    chemicals_price: 7000,
    plastic_price: 3000,
    zone_value: 47000,
    worth_per_arc: 5.22,
    total_raw_material_value: 47000,
    zone_total_value: 47000,
    final_value: 47000,
    generation_output_value: 'Chemicals 5 (35,000 ARK) · Plastic 4 (12,000 ARK)',
    deposits: 'Chemicals, Plastic',
    in_the_ground: 'Chemicals 5 · Plastic 4',
    makes: 'Chemicals 5 · Plastic 4',
    yield: 'Chemicals 5 · Plastic 4 (47,000 ARK)',
    raw_materials: [
      { name: 'Chemicals', quantity: 5, unit: 'loads', price: 7000, total_value: 35000 },
      { name: 'Plastic', quantity: 4, unit: 'loads', price: 3000, total_value: 12000 },
    ],
    // Unlocks in Round 2
    crisis: 'The Model Cannot Be Trusted',
    problem: 'The Oracle has begun returning forecasts that nobody can verify.',
    fix_material: 'Power',
    fix_qty: 8,
    zone_has_it: 'No — this zone holds none',
    space_check: 'Fits. 16 free, 8 needed.',
    if_not_fixed: 'Forecast reliability drops to zero and decision errors cascade.',
    budget: '10000 grant + whatever the team saved',
    // Unlocks in Round 5
    trades: 'Chemicals — the zone holds 5 loads',
    split_a: 'Liquid — 2 loads of chemicals makes 1',
    split_b: 'Powder — 1 load of chemicals makes 1',
    wanted_by: 'Zone 12 wants 4 liquid\nZone 23 wants 4 powder',
    splits_once: true,
    spoils: true,
    round_5_material: 'Chemicals',
    status: 'available',
  },

  // ============================================================
  // ZONE 22 — SWARMBAY
  // ============================================================
  {
    id: 'zone_22',
    zone_number: 22,
    name: 'SWARMBAY',
    region: 'The Grid',
    next_to: '17, 21, 23',
    neighboring_zones: '17, 21, 23',
    starting_price: 16000,
    description: "Swarmbay is ARKK's autonomous drone fleet base.",
    terrain: "Swarmbay is ARKK's autonomous drone fleet base.",
    space: 40,
    stock: 'Metal 14 · Plastic 10',
    used: 24,
    free: 16,
    free_text: '16',
    worth: 'SEALED',
    // Unlocks at The Reveal
    metal_price: 800,
    plastic_price: 3000,
    zone_value: 41200,
    worth_per_arc: 2.58,
    total_raw_material_value: 41200,
    zone_total_value: 41200,
    final_value: 41200,
    generation_output_value: 'Metal 14 (11,200 ARK) · Plastic 10 (30,000 ARK)',
    deposits: 'Metal, Plastic',
    in_the_ground: 'Metal 14 · Plastic 10',
    makes: 'Metal 14 · Plastic 10',
    yield: 'Metal 14 · Plastic 10 (41,200 ARK)',
    raw_materials: [
      { name: 'Metal', quantity: 14, unit: 'loads', price: 800, total_value: 11200 },
      { name: 'Plastic', quantity: 10, unit: 'loads', price: 3000, total_value: 30000 },
    ],
    // Unlocks in Round 2
    crisis: 'The Fleet Is Grounded',
    problem: 'The entire fleet is on the ground.',
    fix_material: 'Glass',
    fix_qty: 20,
    zone_has_it: 'No — this zone holds none',
    space_check: 'DOES NOT FIT. 16 free, 20 needed. Must clear 4 loads first.',
    if_not_fixed: 'Drone operations cease completely and automated patrols collapse.',
    budget: '10000 grant + whatever the team saved',
    // Unlocks in Round 5
    trades: 'Metal — the zone holds 14 loads',
    split_a: 'Beams — 3 loads of metal makes 1',
    split_b: 'Filings — 2 loads of metal makes 1',
    wanted_by: 'Zone 13 wants 6 beams\nZone 9 wants 8 filings',
    splits_once: true,
    spoils: true,
    round_5_material: 'Metal',
    status: 'available',
  },

  // ============================================================
  // ZONE 23 — THE FORGE
  // ============================================================
  {
    id: 'zone_23',
    zone_number: 23,
    name: 'THE FORGE',
    region: 'The Grid',
    next_to: '18, 22, 24',
    neighboring_zones: '18, 22, 24',
    starting_price: 18000,
    description: 'The Forge is a robotic fabrication floor.',
    terrain: 'The Forge is a robotic fabrication floor.',
    space: 35,
    stock: 'Metal 18 · Plastic 8',
    used: 26,
    free: 9,
    free_text: '9',
    worth: 'SEALED',
    // Unlocks at The Reveal
    metal_price: 800,
    plastic_price: 3000,
    zone_value: 38400,
    worth_per_arc: 2.13,
    total_raw_material_value: 38400,
    zone_total_value: 38400,
    final_value: 38400,
    generation_output_value: 'Metal 18 (14,400 ARK) · Plastic 8 (24,000 ARK)',
    deposits: 'Metal, Plastic',
    in_the_ground: 'Metal 18 · Plastic 8',
    makes: 'Metal 18 · Plastic 8',
    yield: 'Metal 18 · Plastic 8 (38,400 ARK)',
    raw_materials: [
      { name: 'Metal', quantity: 18, unit: 'loads', price: 800, total_value: 14400 },
      { name: 'Plastic', quantity: 8, unit: 'loads', price: 3000, total_value: 24000 },
    ],
    // Unlocks in Round 2
    crisis: 'The Arms Have Drifted',
    problem: 'The robotic arms have drifted out of calibration.',
    fix_material: 'Chemicals',
    fix_qty: 4,
    zone_has_it: 'No — this zone holds none',
    space_check: 'Fits. 9 free, 4 needed.',
    if_not_fixed: 'Fabrication lines stall and manufactured components suffer structural failure.',
    budget: '10000 grant + whatever the team saved',
    // Unlocks in Round 5
    trades: 'Metal — the zone holds 18 loads',
    split_a: 'Beams — 3 loads of metal makes 1',
    split_b: 'Filings — 2 loads of metal makes 1',
    wanted_by: 'Zone 11 wants 6 beams\nZone 22 wants 10 filings',
    splits_once: true,
    spoils: true,
    round_5_material: 'Metal',
    status: 'available',
  },

  // ============================================================
  // ZONE 24 — BIOLAB
  // ============================================================
  {
    id: 'zone_24',
    zone_number: 24,
    name: 'BIOLAB',
    region: 'The Grid',
    next_to: '19, 23, 25',
    neighboring_zones: '19, 23, 25',
    starting_price: 12000,
    description: 'Biolab is the only facility on the map that can synthesise new medicine rather than scavenge it.',
    terrain: 'Biolab is the only facility on the map that can synthesise new medicine rather than scavenge it.',
    space: 90,
    stock: 'Medicine 3 · Chemicals 3',
    used: 6,
    free: 84,
    free_text: '84',
    worth: 'SEALED',
    // Unlocks at The Reveal
    medicine_price: 11000,
    chemicals_price: 7000,
    zone_value: 54000,
    worth_per_arc: 4.50,
    total_raw_material_value: 54000,
    zone_total_value: 54000,
    final_value: 54000,
    generation_output_value: 'Medicine 3 (33,000 ARK) · Chemicals 3 (21,000 ARK)',
    deposits: 'Medicine, Chemicals',
    in_the_ground: 'Medicine 3 · Chemicals 3',
    makes: 'Medicine 3 · Chemicals 3',
    yield: 'Medicine 3 · Chemicals 3 (54,000 ARK)',
    raw_materials: [
      { name: 'Medicine', quantity: 3, unit: 'loads', price: 11000, total_value: 33000 },
      { name: 'Chemicals', quantity: 3, unit: 'loads', price: 7000, total_value: 21000 },
    ],
    // Unlocks in Round 2
    crisis: 'The Clean Rooms Are Breached',
    problem: 'A seal has failed and the clean rooms are contaminated.',
    fix_material: 'Water',
    fix_qty: 80,
    zone_has_it: 'No — this zone holds none',
    space_check: 'Fits. 84 free, 80 needed.',
    if_not_fixed: 'Sterile synthesis halts permanently and existing medicine stocks spoil.',
    budget: '10000 grant + whatever the team saved',
    // Unlocks in Round 5
    trades: 'Medicine — the zone holds 3 loads',
    split_a: 'Tablets — 2 loads of medicine makes 1',
    split_b: 'Disinfectant — 1 load of medicine makes 1',
    wanted_by: 'Zone 6 wants 1 tablets\nZone 9 wants 1 disinfectant',
    splits_once: true,
    spoils: true,
    round_5_material: 'Medicine',
    status: 'available',
  },

  // ============================================================
  // ZONE 25 — DEEPNET
  // ============================================================
  {
    id: 'zone_25',
    zone_number: 25,
    name: 'DEEPNET',
    region: 'The Grid',
    next_to: '20, 24',
    neighboring_zones: '20, 24',
    starting_price: 14000,
    description: 'Deepnet is the last working data network on the map.',
    terrain: 'Deepnet is the last working data network on the map.',
    space: 55,
    stock: 'Glass 16 · Power 5',
    used: 21,
    free: 34,
    free_text: '34',
    worth: 'SEALED',
    // Unlocks at The Reveal
    glass_price: 1200,
    power_price: 3500,
    zone_value: 36700,
    worth_per_arc: 2.62,
    total_raw_material_value: 36700,
    zone_total_value: 36700,
    final_value: 36700,
    generation_output_value: 'Glass 16 (19,200 ARK) · Power 5 (17,500 ARK)',
    deposits: 'Glass, Power',
    in_the_ground: 'Glass 16 · Power 5',
    makes: 'Glass 16 · Power 5',
    yield: 'Glass 16 · Power 5 (36,700 ARK)',
    raw_materials: [
      { name: 'Glass', quantity: 16, unit: 'loads', price: 1200, total_value: 19200 },
      { name: 'Power', quantity: 5, unit: 'loads', price: 3500, total_value: 17500 },
    ],
    // Unlocks in Round 2
    crisis: 'The Network Has Been Breached',
    problem: 'Records are being altered from inside the network.',
    fix_material: 'Metal',
    fix_qty: 30,
    zone_has_it: 'No — this zone holds none',
    space_check: 'Fits. 34 free, 30 needed.',
    if_not_fixed: 'Network encryption collapses and core data records are irretrievably corrupted.',
    budget: '10000 grant + whatever the team saved',
    // Unlocks in Round 5
    trades: 'Glass — the zone holds 16 loads',
    split_a: 'Sheets — 2 loads of glass makes 1',
    split_b: 'Sand — 1 load of glass makes 1',
    wanted_by: 'Zone 9 wants 4 sheets\nZone 13 wants 6 sand',
    splits_once: true,
    spoils: true,
    round_5_material: 'Glass',
    status: 'available',
  },
];
